name: upstream-build

on:
  #schedule:
  #  - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - main
    paths:
      - "common/Makefile"
      - "upstream"
  workflow_dispatch:

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: upstream-build
    environment: upstream-build
    timeout-minutes: 300
    # FIXME: change to ubuntu-latest when ubuntu-latest is Ubuntu 26.04.
    runs-on: ubuntu-26.04
    permissions:
      id-token: write # This is required for cosign
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Get Git commit timestamps
        run: |
          TIMESTAMP=$(git log -1 --pretty=%ct .)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Install cosign
        if: github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Configure to push
        if: github.ref == 'refs/heads/main'
        run: |
          echo "PUSH_CMD=docker" >> $GITHUB_ENV
          echo "PUSH_OPTION=--push" >> $GITHUB_ENV
          echo "COSIGN_CMD=cosign" >> $GITHUB_ENV

      - name: Build upstream images
        run: |
          set -o pipefail
          export BUILDKIT_PROGRESS=plain
          export Q=''
          export DOCKER_EXTRA_UPSTREAM_ARGS="--pull --no-cache"
          # Build buildpack-deps/Ubuntu first, but build the other images even if it fails.
          make -k -C upstream DIRS=buildpack-deps -j2 all || true
          # Independent builds, so keep going to get non-failing images updated.
          make -k -C upstream -j2 all
        env:
          CI_REGISTRY: ${{ vars.CI_REGISTRY }}
          CI_REGISTRY_BASE_PATH: ${{ vars.CI_REGISTRY_UPSTREAM_BASE_PATH }}
          COSIGN_CMD: ${{ env.COSIGN_CMD }}
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG_UPSTREAM_RW }}
          ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}
          PUSH_CMD: ${{ env.PUSH_CMD }}
          PUSH_OPTION: ${{ env.PUSH_OPTION }}
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
